name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 19 * * *'  # Daily update at 22:00 MSK
  workflow_dispatch:

jobs:
  build-and-refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
    
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          # Устанавливаем зависимости только если файл существует
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install .
          fi
    
      - name: Run linter
        run: |
          flake8 . --count --show-source --statistics --max-line-length=120 || echo "Flake8 check completed"
          # Запускаем pytest только если есть тесты
          if [ -d "tests" ]; then
            python -m pytest tests/ -v
          else
            echo "No tests directory found"
          fi
    
      - name: Refresh GitHub Stats
        run: |
          TIMESTAMP=$(date +%s)
          STATS_URLS=(
            "https://github-readme-stats.vercel.app/api?username=EgoruZz&show_icons=true&theme=highcontrast&include_all_commits=true&count_private=true&random=$TIMESTAMP"
            "https://github-readme-stats.vercel.app/api/top-langs/?username=EgoruZz&layout=compact&theme=highcontrast&hide=html,css&exclude_repo=README-STATS&random=$TIMESTAMP"
            "https://streak-stats.demolab.com/?user=EgoruZz&theme=highcontrast&random=$TIMESTAMP"
          )
          
          for url in "${STATS_URLS[@]}"; do
            curl -s "$url" > /dev/null && echo "Success: $url" || echo "Failed: $url"
            sleep 2
          done

      - name: Purge CDN Caches
        run: |
          curl -s -X POST "https://purge.jsdelivr.net/gh/EgoruZz/EgoruZz@main/README.md" \
            -H "Content-Type: application/json" \
            -d '{"path":"/README.md"}'
          sleep 5

      - name: Verify Updates
        run: |
          echo "Last refresh: $(date +'%Y-%m-%d %H:%M:%S %Z')"
          echo "Next scheduled: $(date -d '+1 day 22:00' +'%Y-%m-%d %H:%M:%S %Z')"
