name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 18 * * *'  # Ежедневное обновление в 18:00 UTC (21:00 МСК)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: Run linter (flake8)
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics
    
      - name: Update GitHub Stats Cache
        if: github.ref == 'refs/heads/main'
        run: |
          # Принудительное обновление кэша статистики
          curl -s "https://github-readme-stats.vercel.app/api?username=EgoruZz&random=$RANDOM" > /dev/null
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=EgoruZz&layout=compact&random=$RANDOM" > /dev/null
