name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 19 * * *'  # Daily update at 22:00 MSK
  workflow_dispatch:

jobs:
  build-and-refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Устанавливаем только необходимые зависимости, если requirements.txt нет
          pip install flake8 pytest
    
      - name: Run linter
        run: |
          flake8 . --count --show-source --statistics --max-line-length=120
          # Запускаем pytest только если есть папка tests
          if [ -d "tests" ]; then python -m pytest tests/ -v; fi
    
      - name: Refresh GitHub Stats
        if: github.ref == 'refs/heads/main'
        run: |
          # Generate unique cache buster
          TIMESTAMP=$(date +%s)
          
          # Update all stats with multiple fallbacks
          STATS_URLS=(
            "https://github-readme-stats.vercel.app/api?username=EgoruZz&show_icons=true&theme=highcontrast&include_all_commits=true&count_private=true&random=$TIMESTAMP"
            "https://github-readme-stats.vercel.app/api/top-langs/?username=EgoruZz&layout=compact&theme=highcontrast&hide=html,css&exclude_repo=README-STATS&random=$TIMESTAMP"
            "https://streak-stats.demolab.com/?user=EgoruZz&theme=highcontrast&random=$TIMESTAMP"
            "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=EgoruZz&theme=github_dark&random=$TIMESTAMP"
          )
          
          for url in "${STATS_URLS[@]}"; do
            curl -s "$url" > /dev/null && echo "Success: $url" || echo "Failed: $url"
            sleep 2  # Rate limiting protection
          done

      - name: Purge CDN Caches
        run: |
          # Purge multiple CDN endpoints
          curl -s -X POST "https://purge.jsdelivr.net/gh/EgoruZz/EgoruZz@main/README.md" \
            -H "Content-Type: application/json" \
            -d '{"path":"/README.md"}'
          
          curl -s "https://api.github.com/repos/EgoruZz/EgoruZz/dispatches" \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "purge_cache"}'
          
          sleep 5  # Wait for cache invalidation

      - name: Force Readme Update
        run: |
          # Trigger fake update
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md || true
          git commit --allow-empty -m "♻️ Force stats refresh [skip ci]" || true
          git push origin main

      - name: Verify Updates
        run: |
          echo "Last refresh: $(date +'%Y-%m-%d %H:%M:%S %Z')"
          echo "Next scheduled: $(date -d '+1 day 22:00' +'%Y-%m-%d %H:%M:%S %Z')"
          curl -s "https://api.github.com/repos/EgoruZz/EgoruZz/readme" | jq .content | base64 --decode
