name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Generate Metrics
        run: |
          pip install pygithub
          python -c "
          from github import Github
          import os
          
          g = Github(os.getenv('GITHUB_TOKEN'))
          repo = g.get_repo('EgoruZz/EgoruZz')
          
          # Basic metrics calculation
          stars = sum([repo.stargazers_count for repo in g.get_user().get_repos()])
          followers = g.get_user().get_followers().totalCount
          
          # Generate SVG content
          svg_content = f'''
          <svg xmlns="http://www.w3.org/2000/svg" width="400" height="200">
            <rect width="100%" height="100%" fill="#0d1117"/>
            <text x="20" y="30" font-family="Arial" font-size="14" fill="#58a6ff">
              GitHub Stats for EgoruZz
            </text>
            <text x="20" y="60" font-family="Arial" font-size="12" fill="#c9d1d9">
              Total Stars: {stars}
            </text>
            <text x="20" y="90" font-family="Arial" font-size="12" fill="#c9d1d9">
              Followers: {followers}
            </text>
          </svg>
          '''
          
          with open('github-metrics.svg', 'w') as f:
            f.write(svg_content)
          "
          
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-metrics.svg
          git commit -m "Update GitHub metrics" || exit 0
          git push
