name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Ежедневно в полночь UTC
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate basic stats
        run: |
          # Создаем простой SVG с метриками
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="120" viewBox="0 0 400 120">
            <style>.text { font-family: Arial; font-size: 14px; fill: #58a6ff; }</style>
            <rect width="100%" height="100%" fill="#0d1117"/>
            <text x="20" y="30" class="text">GitHub Stats for EgoruZz</text>
            <text x="20" y="60" class="text">Custom metrics coming soon</text>
          </svg>' > metrics.svg
          
          # Коммитим изменения
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add metrics.svg
          git commit -m "Update metrics" || exit 0
          git push
