name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  workflow_dispatch:      # Разрешает ручной запуск

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Необходимо для сохранения SVG
    steps:
      - uses: actions/checkout@v4
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          config_timezone: Europe/Moscow
          base: header, activity, community
          plugin_activity: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_stars: yes
          plugin_lines: yes
          plugin_traffic: yes
